server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Essencial para Single Page Applications - Todas as rotas desconhecidas vão para o index do React
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Desativa log de não encontrados para arquivos secundários úteis
    location = /favicon.ico { log_not_found off; access_log off; }
    location = /robots.txt  { log_not_found off; access_log off; }

    # Tratativa de caches estáticos (Assets - JS, CSS, Media)
    location ~* \.(?:css|js|map|jpe?g|gif|png|webp|svg|woff2?|eot|ttf|otf|ico)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }
}
